env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - airbnb/hooks
  - prettier
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
  - import
rules:
  react/react-in-jsx-scope: off
  import/extensions:
    - error
    - ts: never
      tsx: never
      js: never
      jsx: never
  import/prefer-default-export: off
settings:
  import/resolver:
    typescript: {}
